import fitz  # PyMuPDF for PDFs
from docx import Document
import pandas as pd
from transformers import pipeline

# Load NLP model for text classification
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Function to classify text as Header or Content using NLP
def classify_text(text):
    labels = ["Header", "Content"]
        classification = classifier(text, candidate_labels=labels)
            return classification['labels'][0]  # Returns "Header" or "Content"

            # Function to extract headers & values from PDFs
            def extract_headers_from_pdf(pdf_path):
                doc = fitz.open(pdf_path)
                    sections = []
                        current_section = None

                            for page in doc:
                                    blocks = page.get_text("dict")["blocks"]
                                            for block in blocks:
                                                        for line in block.get("lines", []):
                                                                        for span in line.get("spans", []):
                                                                                            text = span["text"].strip()
                                                                                                                font_size = span["size"]
                                                                                                                                    is_bold = "bold" in span["font"].lower()

                                                                                                                                                        # Use NLP classification for better accuracy
                                                                                                                                                                            label = classify_text(text)

                                                                                                                                                                                                if label == "Header":
                                                                                                                                                                                                                        if current_section:
                                                                                                                                                                                                                                                    sections.append(current_section)
                                                                                                                                                                                                                                                                            current_section = {"Header": text, "Content": ""}
                                                                                                                                                                                                                                                                                                elif current_section:
                                                                                                                                                                                                                                                                                                                        current_section["Content"] += text + " "

                                                                                                                                                                                                                                                                                                                            if current_section:
                                                                                                                                                                                                                                                                                                                                    sections.append(current_section)

                                                                                                                                                                                                                                                                                                                                        return sections

                                                                                                                                                                                                                                                                                                                                        # Function to extract headers & values from DOCX
                                                                                                                                                                                                                                                                                                                                        def extract_headers_from_docx(docx_path):
                                                                                                                                                                                                                                                                                                                                            doc = Document(docx_path)
                                                                                                                                                                                                                                                                                                                                                sections = []
                                                                                                                                                                                                                                                                                                                                                    current_section = None

                                                                                                                                                                                                                                                                                                                                                        for para in doc.paragraphs:
                                                                                                                                                                                                                                                                                                                                                                text = para.text.strip()
                                                                                                                                                                                                                                                                                                                                                                        is_bold = any(run.bold for run in para.runs if run.text.strip())
                                                                                                                                                                                                                                                                                                                                                                                is_heading = para.style.name.startswith("Heading")

                                                                                                                                                                                                                                                                                                                                                                                        # Use NLP classification for better accuracy
                                                                                                                                                                                                                                                                                                                                                                                                label = classify_text(text)

                                                                                                                                                                                                                                                                                                                                                                                                        if label == "Header" or is_heading or is_bold:
                                                                                                                                                                                                                                                                                                                                                                                                                    if current_section:
                                                                                                                                                                                                                                                                                                                                                                                                                                    sections.append(current_section)
                                                                                                                                                                                                                                                                                                                                                                                                                                                current_section = {"Header": text, "Content": ""}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif current_section:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    current_section["Content"] += text + " "

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if current_section:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sections.append(current_section)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return sections

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Function to handle any document type
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def extract_headers_from_document(file_path, file_type):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if file_type.lower() == "pdf":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return extract_headers_from_pdf(file_path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif file_type.lower() == "docx":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return extract_headers_from_docx(file_path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Unsupported file type.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return []

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Example Usage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pdf_data = extract_headers_from_document("sample.pdf", "pdf")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                docx_data = extract_headers_from_document("sample.docx", "docx")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Convert to DataFrame for structured output
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                df_pdf = pd.DataFrame(pdf_data, columns=["Header", "Content"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                df_docx = pd.DataFrame(docx_data, columns=["Header", "Content"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Save to CSV for easy analysis
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                df_pdf.to_csv("pdf_extracted_data.csv", index=False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                df_docx.to_csv("docx_extracted_data.csv", index=False)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Extraction complete! Data saved as structured CSV.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                