import pdfplumber
import fitz  # PyMuPDF
import re

def extract_headers_from_pdf(pdf_path):
    """Extract headers and their respective content from a PDF using pdfplumber + PyMuPDF"""
        extracted_data = []
            current_header = None
                current_content = []

                    with pdfplumber.open(pdf_path) as pdf:
                            doc = fitz.open(pdf_path)  # Load PyMuPDF
                                    for page_num, page in enumerate(pdf.pages):
                                                text = page.extract_text()
                                                            if not text:
                                                                            continue

                                                                                        lines = text.split("\n")
                                                                                                    page_fonts = extract_fonts(doc[page_num])  # Extract font info using PyMuPDF
                                                                                                                
                                                                                                                            for i, line in enumerate(lines):
                                                                                                                                            line = line.strip()
                                                                                                                                                            if not line:
                                                                                                                                                                                continue  # Skip empty lines
                                                                                                                                                                                                
                                                                                                                                                                                                                # Detect headers (numbers or bold text)
                                                                                                                                                                                                                                is_numbered = bool(re.match(r'^\d+(\.\d+)*\)?\s+', line))  
                                                                                                                                                                                                                                                is_bullet = bool(re.match(r'^[-*•]\s+', line))  
                                                                                                                                                                                                                                                                is_bold = page_fonts.get(i, {}).get("bold", False)  # Check if the text is bold
                                                                                                                                                                                                                                                                                is_larger_font = page_fonts.get(i, {}).get("size", 0) > page_fonts.get(i - 1, {}).get("size", 0)

                                                                                                                                                                                                                                                                                                # Identify headers
                                                                                                                                                                                                                                                                                                                if is_numbered or is_bullet or (is_bold and is_larger_font):
                                                                                                                                                                                                                                                                                                                                    if current_header:
                                                                                                                                                                                                                                                                                                                                                            extracted_data.append((current_header, "\n".join(current_content)))  # Save previous section
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    current_header = line
                                                                                                                                                                                                                                                                                                                                                                                                                        current_content = []
                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            current_content.append(line)  # Append content under the last header

                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Save last section
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if current_header:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            extracted_data.append((current_header, "\n".join(current_content)))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return extracted_data

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def extract_fonts(page):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Extract font size and bold status using PyMuPDF (fitz)"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font_data = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            blocks = page.get_text("dict")["blocks"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for block in blocks:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for line in block.get("lines", []):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for span in line.get("spans", []):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    index = len(font_data)  # Track line index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    font_data[index] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "size": span["size"], 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "bold": "Bold" in span["font"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return font_data

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Example Usage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pdf_path = "sample.pdf"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                headers_content = extract_headers_from_pdf(pdf_path)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Print results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for header, content in headers_content:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"HEADER: {header}\nCONTENT: {content}\n{'='*50}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    